/**
 * Cherwell Rest API
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CherwellRestApi) {
      root.CherwellRestApi = {};
    }
    root.CherwellRestApi.AttachmentsRequest = factory(root.CherwellRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AttachmentsRequest model module.
   * @module model/AttachmentsRequest
   * @version 9.2.0
   */

  /**
   * Constructs a new <code>AttachmentsRequest</code>.
   * @alias module:model/AttachmentsRequest
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>AttachmentsRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AttachmentsRequest} obj Optional instance to populate.
   * @return {module:model/AttachmentsRequest} The populated <code>AttachmentsRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('attachmentId')) {
        obj['attachmentId'] = ApiClient.convertToType(data['attachmentId'], 'String');
      }
      if (data.hasOwnProperty('attachmentTypes')) {
        obj['attachmentTypes'] = ApiClient.convertToType(data['attachmentTypes'], ['String']);
      }
      if (data.hasOwnProperty('busObId')) {
        obj['busObId'] = ApiClient.convertToType(data['busObId'], 'String');
      }
      if (data.hasOwnProperty('busObName')) {
        obj['busObName'] = ApiClient.convertToType(data['busObName'], 'String');
      }
      if (data.hasOwnProperty('busObPublicId')) {
        obj['busObPublicId'] = ApiClient.convertToType(data['busObPublicId'], 'String');
      }
      if (data.hasOwnProperty('busObRecId')) {
        obj['busObRecId'] = ApiClient.convertToType(data['busObRecId'], 'String');
      }
      if (data.hasOwnProperty('includeLinks')) {
        obj['includeLinks'] = ApiClient.convertToType(data['includeLinks'], 'Boolean');
      }
      if (data.hasOwnProperty('types')) {
        obj['types'] = ApiClient.convertToType(data['types'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {String} attachmentId
   */
  exports.prototype['attachmentId'] = undefined;
  /**
   * @member {Array.<module:model/AttachmentsRequest.AttachmentTypesEnum>} attachmentTypes
   */
  exports.prototype['attachmentTypes'] = undefined;
  /**
   * @member {String} busObId
   */
  exports.prototype['busObId'] = undefined;
  /**
   * @member {String} busObName
   */
  exports.prototype['busObName'] = undefined;
  /**
   * @member {String} busObPublicId
   */
  exports.prototype['busObPublicId'] = undefined;
  /**
   * @member {String} busObRecId
   */
  exports.prototype['busObRecId'] = undefined;
  /**
   * @member {Boolean} includeLinks
   */
  exports.prototype['includeLinks'] = undefined;
  /**
   * @member {Array.<module:model/AttachmentsRequest.TypesEnum>} types
   */
  exports.prototype['types'] = undefined;


  /**
   * Allowed values for the <code>attachmentTypes</code> property.
   * @enum {String}
   * @readonly
   */
  exports.AttachmentTypesEnum = {
    /**
     * value: "Imported"
     * @const
     */
    "Imported": "Imported",
    /**
     * value: "Linked"
     * @const
     */
    "Linked": "Linked",
    /**
     * value: "URL"
     * @const
     */
    "URL": "URL"  };

  /**
   * Allowed values for the <code>types</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypesEnum = {
    /**
     * value: "None"
     * @const
     */
    "None": "None",
    /**
     * value: "File"
     * @const
     */
    "File": "File",
    /**
     * value: "FileManagerFile"
     * @const
     */
    "FileManagerFile": "FileManagerFile",
    /**
     * value: "BusOb"
     * @const
     */
    "BusOb": "BusOb",
    /**
     * value: "History"
     * @const
     */
    "History": "History",
    /**
     * value: "Other"
     * @const
     */
    "Other": "Other"  };


  return exports;
}));


