/**
 * Cherwell Rest API
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FilterInfo', 'model/PromptValue', 'model/SortInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FilterInfo'), require('./PromptValue'), require('./SortInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.CherwellRestApi) {
      root.CherwellRestApi = {};
    }
    root.CherwellRestApi.ExportSearchResultsRequest = factory(root.CherwellRestApi.ApiClient, root.CherwellRestApi.FilterInfo, root.CherwellRestApi.PromptValue, root.CherwellRestApi.SortInfo);
  }
}(this, function(ApiClient, FilterInfo, PromptValue, SortInfo) {
  'use strict';




  /**
   * The ExportSearchResultsRequest model module.
   * @module model/ExportSearchResultsRequest
   * @version 9.2.0
   */

  /**
   * Constructs a new <code>ExportSearchResultsRequest</code>.
   * @alias module:model/ExportSearchResultsRequest
   * @class
   */
  var exports = function() {
    var _this = this;






















  };

  /**
   * Constructs a <code>ExportSearchResultsRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExportSearchResultsRequest} obj Optional instance to populate.
   * @return {module:model/ExportSearchResultsRequest} The populated <code>ExportSearchResultsRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('customSeparator')) {
        obj['customSeparator'] = ApiClient.convertToType(data['customSeparator'], 'String');
      }
      if (data.hasOwnProperty('exportFormat')) {
        obj['exportFormat'] = ApiClient.convertToType(data['exportFormat'], 'String');
      }
      if (data.hasOwnProperty('exportTitle')) {
        obj['exportTitle'] = ApiClient.convertToType(data['exportTitle'], 'String');
      }
      if (data.hasOwnProperty('association')) {
        obj['association'] = ApiClient.convertToType(data['association'], 'String');
      }
      if (data.hasOwnProperty('busObId')) {
        obj['busObId'] = ApiClient.convertToType(data['busObId'], 'String');
      }
      if (data.hasOwnProperty('customGridDefId')) {
        obj['customGridDefId'] = ApiClient.convertToType(data['customGridDefId'], 'String');
      }
      if (data.hasOwnProperty('dateTimeFormatting')) {
        obj['dateTimeFormatting'] = ApiClient.convertToType(data['dateTimeFormatting'], 'String');
      }
      if (data.hasOwnProperty('fieldId')) {
        obj['fieldId'] = ApiClient.convertToType(data['fieldId'], 'String');
      }
      if (data.hasOwnProperty('fields')) {
        obj['fields'] = ApiClient.convertToType(data['fields'], ['String']);
      }
      if (data.hasOwnProperty('filters')) {
        obj['filters'] = ApiClient.convertToType(data['filters'], [FilterInfo]);
      }
      if (data.hasOwnProperty('includeAllFields')) {
        obj['includeAllFields'] = ApiClient.convertToType(data['includeAllFields'], 'Boolean');
      }
      if (data.hasOwnProperty('includeSchema')) {
        obj['includeSchema'] = ApiClient.convertToType(data['includeSchema'], 'Boolean');
      }
      if (data.hasOwnProperty('pageNumber')) {
        obj['pageNumber'] = ApiClient.convertToType(data['pageNumber'], 'Number');
      }
      if (data.hasOwnProperty('pageSize')) {
        obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
      }
      if (data.hasOwnProperty('scope')) {
        obj['scope'] = ApiClient.convertToType(data['scope'], 'String');
      }
      if (data.hasOwnProperty('scopeOwner')) {
        obj['scopeOwner'] = ApiClient.convertToType(data['scopeOwner'], 'String');
      }
      if (data.hasOwnProperty('searchId')) {
        obj['searchId'] = ApiClient.convertToType(data['searchId'], 'String');
      }
      if (data.hasOwnProperty('searchName')) {
        obj['searchName'] = ApiClient.convertToType(data['searchName'], 'String');
      }
      if (data.hasOwnProperty('searchText')) {
        obj['searchText'] = ApiClient.convertToType(data['searchText'], 'String');
      }
      if (data.hasOwnProperty('sorting')) {
        obj['sorting'] = ApiClient.convertToType(data['sorting'], [SortInfo]);
      }
      if (data.hasOwnProperty('promptValues')) {
        obj['promptValues'] = ApiClient.convertToType(data['promptValues'], [PromptValue]);
      }
    }
    return obj;
  }

  /**
   * @member {String} customSeparator
   */
  exports.prototype['customSeparator'] = undefined;
  /**
   * @member {module:model/ExportSearchResultsRequest.ExportFormatEnum} exportFormat
   */
  exports.prototype['exportFormat'] = undefined;
  /**
   * @member {String} exportTitle
   */
  exports.prototype['exportTitle'] = undefined;
  /**
   * @member {String} association
   */
  exports.prototype['association'] = undefined;
  /**
   * @member {String} busObId
   */
  exports.prototype['busObId'] = undefined;
  /**
   * @member {String} customGridDefId
   */
  exports.prototype['customGridDefId'] = undefined;
  /**
   * @member {String} dateTimeFormatting
   */
  exports.prototype['dateTimeFormatting'] = undefined;
  /**
   * @member {String} fieldId
   */
  exports.prototype['fieldId'] = undefined;
  /**
   * @member {Array.<String>} fields
   */
  exports.prototype['fields'] = undefined;
  /**
   * @member {Array.<module:model/FilterInfo>} filters
   */
  exports.prototype['filters'] = undefined;
  /**
   * @member {Boolean} includeAllFields
   */
  exports.prototype['includeAllFields'] = undefined;
  /**
   * @member {Boolean} includeSchema
   */
  exports.prototype['includeSchema'] = undefined;
  /**
   * @member {Number} pageNumber
   */
  exports.prototype['pageNumber'] = undefined;
  /**
   * @member {Number} pageSize
   */
  exports.prototype['pageSize'] = undefined;
  /**
   * @member {String} scope
   */
  exports.prototype['scope'] = undefined;
  /**
   * @member {String} scopeOwner
   */
  exports.prototype['scopeOwner'] = undefined;
  /**
   * @member {String} searchId
   */
  exports.prototype['searchId'] = undefined;
  /**
   * @member {String} searchName
   */
  exports.prototype['searchName'] = undefined;
  /**
   * @member {String} searchText
   */
  exports.prototype['searchText'] = undefined;
  /**
   * @member {Array.<module:model/SortInfo>} sorting
   */
  exports.prototype['sorting'] = undefined;
  /**
   * @member {Array.<module:model/PromptValue>} promptValues
   */
  exports.prototype['promptValues'] = undefined;


  /**
   * Allowed values for the <code>exportFormat</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ExportFormatEnum = {
    /**
     * value: "CSV"
     * @const
     */
    "CSV": "CSV",
    /**
     * value: "Excel"
     * @const
     */
    "Excel": "Excel",
    /**
     * value: "Tab"
     * @const
     */
    "Tab": "Tab",
    /**
     * value: "Word"
     * @const
     */
    "Word": "Word",
    /**
     * value: "CustomSeparator"
     * @const
     */
    "CustomSeparator": "CustomSeparator",
    /**
     * value: "Json"
     * @const
     */
    "Json": "Json"  };


  return exports;
}));


