/**
 * Cherwell Rest API
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelObject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelObject'));
  } else {
    // Browser globals (root is window)
    if (!root.CherwellRestApi) {
      root.CherwellRestApi = {};
    }
    root.CherwellRestApi.LogRequest = factory(root.CherwellRestApi.ApiClient, root.CherwellRestApi.ModelObject);
  }
}(this, function(ApiClient, ModelObject) {
  'use strict';




  /**
   * The LogRequest model module.
   * @module model/LogRequest
   * @version 9.2.0
   */

  /**
   * Constructs a new <code>LogRequest</code>.
   * @alias module:model/LogRequest
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>LogRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LogRequest} obj Optional instance to populate.
   * @return {module:model/LogRequest} The populated <code>LogRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('keyValueProperties')) {
        obj['keyValueProperties'] = ApiClient.convertToType(data['keyValueProperties'], [ModelObject]);
      }
      if (data.hasOwnProperty('level')) {
        obj['level'] = ApiClient.convertToType(data['level'], 'String');
      }
      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/ModelObject>} keyValueProperties
   */
  exports.prototype['keyValueProperties'] = undefined;
  /**
   * @member {module:model/LogRequest.LevelEnum} level
   */
  exports.prototype['level'] = undefined;
  /**
   * @member {String} message
   */
  exports.prototype['message'] = undefined;


  /**
   * Allowed values for the <code>level</code> property.
   * @enum {String}
   * @readonly
   */
  exports.LevelEnum = {
    /**
     * value: "Fatal"
     * @const
     */
    "Fatal": "Fatal",
    /**
     * value: "Error"
     * @const
     */
    "Error": "Error",
    /**
     * value: "Warning"
     * @const
     */
    "Warning": "Warning",
    /**
     * value: "Info"
     * @const
     */
    "Info": "Info",
    /**
     * value: "Stats"
     * @const
     */
    "Stats": "Stats",
    /**
     * value: "Debug"
     * @const
     */
    "Debug": "Debug"  };


  return exports;
}));


