/**
 * Cherwell Rest API
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/QuickSearchItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./QuickSearchItem'));
  } else {
    // Browser globals (root is window)
    if (!root.CherwellRestApi) {
      root.CherwellRestApi = {};
    }
    root.CherwellRestApi.QuickSearchConfigurationResponse = factory(root.CherwellRestApi.ApiClient, root.CherwellRestApi.QuickSearchItem);
  }
}(this, function(ApiClient, QuickSearchItem) {
  'use strict';




  /**
   * The QuickSearchConfigurationResponse model module.
   * @module model/QuickSearchConfigurationResponse
   * @version 9.2.0
   */

  /**
   * Constructs a new <code>QuickSearchConfigurationResponse</code>.
   * @alias module:model/QuickSearchConfigurationResponse
   * @class
   */
  var exports = function() {
    var _this = this;



















  };

  /**
   * Constructs a <code>QuickSearchConfigurationResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/QuickSearchConfigurationResponse} obj Optional instance to populate.
   * @return {module:model/QuickSearchConfigurationResponse} The populated <code>QuickSearchConfigurationResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('allowQuickSearch')) {
        obj['allowQuickSearch'] = ApiClient.convertToType(data['allowQuickSearch'], 'Boolean');
      }
      if (data.hasOwnProperty('allowSpecificSearch')) {
        obj['allowSpecificSearch'] = ApiClient.convertToType(data['allowSpecificSearch'], 'Boolean');
      }
      if (data.hasOwnProperty('defaultToQuickSearch')) {
        obj['defaultToQuickSearch'] = ApiClient.convertToType(data['defaultToQuickSearch'], 'Boolean');
      }
      if (data.hasOwnProperty('displayName')) {
        obj['displayName'] = ApiClient.convertToType(data['displayName'], 'String');
      }
      if (data.hasOwnProperty('galleryImage')) {
        obj['galleryImage'] = ApiClient.convertToType(data['galleryImage'], 'String');
      }
      if (data.hasOwnProperty('history')) {
        obj['history'] = ApiClient.convertToType(data['history'], ['String']);
      }
      if (data.hasOwnProperty('includeAvailableInSpecific')) {
        obj['includeAvailableInSpecific'] = ApiClient.convertToType(data['includeAvailableInSpecific'], 'Boolean');
      }
      if (data.hasOwnProperty('includeQuickSearchInSpecific')) {
        obj['includeQuickSearchInSpecific'] = ApiClient.convertToType(data['includeQuickSearchInSpecific'], 'Boolean');
      }
      if (data.hasOwnProperty('quickSearchId')) {
        obj['quickSearchId'] = ApiClient.convertToType(data['quickSearchId'], 'String');
      }
      if (data.hasOwnProperty('quickSearchItems')) {
        obj['quickSearchItems'] = ApiClient.convertToType(data['quickSearchItems'], [QuickSearchItem]);
      }
      if (data.hasOwnProperty('quickSearchWatermark')) {
        obj['quickSearchWatermark'] = ApiClient.convertToType(data['quickSearchWatermark'], 'String');
      }
      if (data.hasOwnProperty('resolvedQuickSearchWatermark')) {
        obj['resolvedQuickSearchWatermark'] = ApiClient.convertToType(data['resolvedQuickSearchWatermark'], 'String');
      }
      if (data.hasOwnProperty('scope')) {
        obj['scope'] = ApiClient.convertToType(data['scope'], 'String');
      }
      if (data.hasOwnProperty('scopeOwner')) {
        obj['scopeOwner'] = ApiClient.convertToType(data['scopeOwner'], 'String');
      }
      if (data.hasOwnProperty('specificSearchItems')) {
        obj['specificSearchItems'] = ApiClient.convertToType(data['specificSearchItems'], [QuickSearchItem]);
      }
      if (data.hasOwnProperty('errorCode')) {
        obj['errorCode'] = ApiClient.convertToType(data['errorCode'], 'String');
      }
      if (data.hasOwnProperty('errorMessage')) {
        obj['errorMessage'] = ApiClient.convertToType(data['errorMessage'], 'String');
      }
      if (data.hasOwnProperty('hasError')) {
        obj['hasError'] = ApiClient.convertToType(data['hasError'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} allowQuickSearch
   */
  exports.prototype['allowQuickSearch'] = undefined;
  /**
   * @member {Boolean} allowSpecificSearch
   */
  exports.prototype['allowSpecificSearch'] = undefined;
  /**
   * @member {Boolean} defaultToQuickSearch
   */
  exports.prototype['defaultToQuickSearch'] = undefined;
  /**
   * @member {String} displayName
   */
  exports.prototype['displayName'] = undefined;
  /**
   * @member {String} galleryImage
   */
  exports.prototype['galleryImage'] = undefined;
  /**
   * @member {Array.<String>} history
   */
  exports.prototype['history'] = undefined;
  /**
   * @member {Boolean} includeAvailableInSpecific
   */
  exports.prototype['includeAvailableInSpecific'] = undefined;
  /**
   * @member {Boolean} includeQuickSearchInSpecific
   */
  exports.prototype['includeQuickSearchInSpecific'] = undefined;
  /**
   * @member {String} quickSearchId
   */
  exports.prototype['quickSearchId'] = undefined;
  /**
   * @member {Array.<module:model/QuickSearchItem>} quickSearchItems
   */
  exports.prototype['quickSearchItems'] = undefined;
  /**
   * @member {String} quickSearchWatermark
   */
  exports.prototype['quickSearchWatermark'] = undefined;
  /**
   * @member {String} resolvedQuickSearchWatermark
   */
  exports.prototype['resolvedQuickSearchWatermark'] = undefined;
  /**
   * @member {String} scope
   */
  exports.prototype['scope'] = undefined;
  /**
   * @member {String} scopeOwner
   */
  exports.prototype['scopeOwner'] = undefined;
  /**
   * @member {Array.<module:model/QuickSearchItem>} specificSearchItems
   */
  exports.prototype['specificSearchItems'] = undefined;
  /**
   * @member {String} errorCode
   */
  exports.prototype['errorCode'] = undefined;
  /**
   * @member {String} errorMessage
   */
  exports.prototype['errorMessage'] = undefined;
  /**
   * @member {Boolean} hasError
   */
  exports.prototype['hasError'] = undefined;



  return exports;
}));


