/**
 * Cherwell Rest API
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Link', 'model/ReadResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Link'), require('./ReadResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.CherwellRestApi) {
      root.CherwellRestApi = {};
    }
    root.CherwellRestApi.RelatedBusinessObjectResponse = factory(root.CherwellRestApi.ApiClient, root.CherwellRestApi.Link, root.CherwellRestApi.ReadResponse);
  }
}(this, function(ApiClient, Link, ReadResponse) {
  'use strict';




  /**
   * The RelatedBusinessObjectResponse model module.
   * @module model/RelatedBusinessObjectResponse
   * @version 9.2.0
   */

  /**
   * Constructs a new <code>RelatedBusinessObjectResponse</code>.
   * @alias module:model/RelatedBusinessObjectResponse
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>RelatedBusinessObjectResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RelatedBusinessObjectResponse} obj Optional instance to populate.
   * @return {module:model/RelatedBusinessObjectResponse} The populated <code>RelatedBusinessObjectResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('errorCode')) {
        obj['errorCode'] = ApiClient.convertToType(data['errorCode'], 'String');
      }
      if (data.hasOwnProperty('errorMessage')) {
        obj['errorMessage'] = ApiClient.convertToType(data['errorMessage'], 'String');
      }
      if (data.hasOwnProperty('hasError')) {
        obj['hasError'] = ApiClient.convertToType(data['hasError'], 'Boolean');
      }
      if (data.hasOwnProperty('links')) {
        obj['links'] = ApiClient.convertToType(data['links'], [Link]);
      }
      if (data.hasOwnProperty('pageNumber')) {
        obj['pageNumber'] = ApiClient.convertToType(data['pageNumber'], 'Number');
      }
      if (data.hasOwnProperty('pageSize')) {
        obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
      }
      if (data.hasOwnProperty('parentBusObId')) {
        obj['parentBusObId'] = ApiClient.convertToType(data['parentBusObId'], 'String');
      }
      if (data.hasOwnProperty('parentBusObPublicId')) {
        obj['parentBusObPublicId'] = ApiClient.convertToType(data['parentBusObPublicId'], 'String');
      }
      if (data.hasOwnProperty('parentBusObRecId')) {
        obj['parentBusObRecId'] = ApiClient.convertToType(data['parentBusObRecId'], 'String');
      }
      if (data.hasOwnProperty('relatedBusinessObjects')) {
        obj['relatedBusinessObjects'] = ApiClient.convertToType(data['relatedBusinessObjects'], [ReadResponse]);
      }
      if (data.hasOwnProperty('relationshipId')) {
        obj['relationshipId'] = ApiClient.convertToType(data['relationshipId'], 'String');
      }
      if (data.hasOwnProperty('totalRecords')) {
        obj['totalRecords'] = ApiClient.convertToType(data['totalRecords'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} errorCode
   */
  exports.prototype['errorCode'] = undefined;
  /**
   * @member {String} errorMessage
   */
  exports.prototype['errorMessage'] = undefined;
  /**
   * @member {Boolean} hasError
   */
  exports.prototype['hasError'] = undefined;
  /**
   * @member {Array.<module:model/Link>} links
   */
  exports.prototype['links'] = undefined;
  /**
   * @member {Number} pageNumber
   */
  exports.prototype['pageNumber'] = undefined;
  /**
   * @member {Number} pageSize
   */
  exports.prototype['pageSize'] = undefined;
  /**
   * @member {String} parentBusObId
   */
  exports.prototype['parentBusObId'] = undefined;
  /**
   * @member {String} parentBusObPublicId
   */
  exports.prototype['parentBusObPublicId'] = undefined;
  /**
   * @member {String} parentBusObRecId
   */
  exports.prototype['parentBusObRecId'] = undefined;
  /**
   * @member {Array.<module:model/ReadResponse>} relatedBusinessObjects
   */
  exports.prototype['relatedBusinessObjects'] = undefined;
  /**
   * @member {String} relationshipId
   */
  exports.prototype['relationshipId'] = undefined;
  /**
   * @member {Number} totalRecords
   */
  exports.prototype['totalRecords'] = undefined;



  return exports;
}));


