/**
 * Cherwell Rest API
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CherwellRestApi) {
      root.CherwellRestApi = {};
    }
    root.CherwellRestApi.SaveStoredValueRequest = factory(root.CherwellRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SaveStoredValueRequest model module.
   * @module model/SaveStoredValueRequest
   * @version 9.2.0
   */

  /**
   * Constructs a new <code>SaveStoredValueRequest</code>.
   * @alias module:model/SaveStoredValueRequest
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>SaveStoredValueRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SaveStoredValueRequest} obj Optional instance to populate.
   * @return {module:model/SaveStoredValueRequest} The populated <code>SaveStoredValueRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('folder')) {
        obj['folder'] = ApiClient.convertToType(data['folder'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('scope')) {
        obj['scope'] = ApiClient.convertToType(data['scope'], 'String');
      }
      if (data.hasOwnProperty('scopeOwner')) {
        obj['scopeOwner'] = ApiClient.convertToType(data['scopeOwner'], 'String');
      }
      if (data.hasOwnProperty('standInKey')) {
        obj['standInKey'] = ApiClient.convertToType(data['standInKey'], 'String');
      }
      if (data.hasOwnProperty('storedValueType')) {
        obj['storedValueType'] = ApiClient.convertToType(data['storedValueType'], 'String');
      }
      if (data.hasOwnProperty('value')) {
        obj['value'] = ApiClient.convertToType(data['value'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {String} folder
   */
  exports.prototype['folder'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} scope
   */
  exports.prototype['scope'] = undefined;
  /**
   * @member {String} scopeOwner
   */
  exports.prototype['scopeOwner'] = undefined;
  /**
   * @member {String} standInKey
   */
  exports.prototype['standInKey'] = undefined;
  /**
   * @member {module:model/SaveStoredValueRequest.StoredValueTypeEnum} storedValueType
   */
  exports.prototype['storedValueType'] = undefined;
  /**
   * @member {String} value
   */
  exports.prototype['value'] = undefined;


  /**
   * Allowed values for the <code>storedValueType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StoredValueTypeEnum = {
    /**
     * value: "Text"
     * @const
     */
    "Text": "Text",
    /**
     * value: "Number"
     * @const
     */
    "Number": "Number",
    /**
     * value: "DateTime"
     * @const
     */
    "DateTime": "DateTime",
    /**
     * value: "Logical"
     * @const
     */
    "Logical": "Logical",
    /**
     * value: "Color"
     * @const
     */
    "Color": "Color",
    /**
     * value: "Json"
     * @const
     */
    "Json": "Json",
    /**
     * value: "JsonArray"
     * @const
     */
    "JsonArray": "JsonArray",
    /**
     * value: "Xml"
     * @const
     */
    "Xml": "Xml",
    /**
     * value: "XmlCollection"
     * @const
     */
    "XmlCollection": "XmlCollection"  };


  return exports;
}));


