/**
 * Cherwell Rest API
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FieldValidationError', 'model/NotificationTrigger'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FieldValidationError'), require('./NotificationTrigger'));
  } else {
    // Browser globals (root is window)
    if (!root.CherwellRestApi) {
      root.CherwellRestApi = {};
    }
    root.CherwellRestApi.SaveResponse = factory(root.CherwellRestApi.ApiClient, root.CherwellRestApi.FieldValidationError, root.CherwellRestApi.NotificationTrigger);
  }
}(this, function(ApiClient, FieldValidationError, NotificationTrigger) {
  'use strict';




  /**
   * The SaveResponse model module.
   * @module model/SaveResponse
   * @version 9.2.0
   */

  /**
   * Constructs a new <code>SaveResponse</code>.
   * @alias module:model/SaveResponse
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>SaveResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SaveResponse} obj Optional instance to populate.
   * @return {module:model/SaveResponse} The populated <code>SaveResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('busObPublicId')) {
        obj['busObPublicId'] = ApiClient.convertToType(data['busObPublicId'], 'String');
      }
      if (data.hasOwnProperty('busObRecId')) {
        obj['busObRecId'] = ApiClient.convertToType(data['busObRecId'], 'String');
      }
      if (data.hasOwnProperty('cacheKey')) {
        obj['cacheKey'] = ApiClient.convertToType(data['cacheKey'], 'String');
      }
      if (data.hasOwnProperty('fieldValidationErrors')) {
        obj['fieldValidationErrors'] = ApiClient.convertToType(data['fieldValidationErrors'], [FieldValidationError]);
      }
      if (data.hasOwnProperty('notificationTriggers')) {
        obj['notificationTriggers'] = ApiClient.convertToType(data['notificationTriggers'], [NotificationTrigger]);
      }
      if (data.hasOwnProperty('errorCode')) {
        obj['errorCode'] = ApiClient.convertToType(data['errorCode'], 'String');
      }
      if (data.hasOwnProperty('errorMessage')) {
        obj['errorMessage'] = ApiClient.convertToType(data['errorMessage'], 'String');
      }
      if (data.hasOwnProperty('hasError')) {
        obj['hasError'] = ApiClient.convertToType(data['hasError'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {String} busObPublicId
   */
  exports.prototype['busObPublicId'] = undefined;
  /**
   * @member {String} busObRecId
   */
  exports.prototype['busObRecId'] = undefined;
  /**
   * @member {String} cacheKey
   */
  exports.prototype['cacheKey'] = undefined;
  /**
   * @member {Array.<module:model/FieldValidationError>} fieldValidationErrors
   */
  exports.prototype['fieldValidationErrors'] = undefined;
  /**
   * @member {Array.<module:model/NotificationTrigger>} notificationTriggers
   */
  exports.prototype['notificationTriggers'] = undefined;
  /**
   * @member {String} errorCode
   */
  exports.prototype['errorCode'] = undefined;
  /**
   * @member {String} errorMessage
   */
  exports.prototype['errorMessage'] = undefined;
  /**
   * @member {Boolean} hasError
   */
  exports.prototype['hasError'] = undefined;



  return exports;
}));


