/**
 * Cherwell Rest API
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CherwellRestApi) {
      root.CherwellRestApi = {};
    }
    root.CherwellRestApi.SaveTeamMemberRequest = factory(root.CherwellRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SaveTeamMemberRequest model module.
   * @module model/SaveTeamMemberRequest
   * @version 9.2.0
   */

  /**
   * Constructs a new <code>SaveTeamMemberRequest</code>.
   * @alias module:model/SaveTeamMemberRequest
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>SaveTeamMemberRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SaveTeamMemberRequest} obj Optional instance to populate.
   * @return {module:model/SaveTeamMemberRequest} The populated <code>SaveTeamMemberRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('isTeamManager')) {
        obj['isTeamManager'] = ApiClient.convertToType(data['isTeamManager'], 'Boolean');
      }
      if (data.hasOwnProperty('setAsDefaultTeam')) {
        obj['setAsDefaultTeam'] = ApiClient.convertToType(data['setAsDefaultTeam'], 'Boolean');
      }
      if (data.hasOwnProperty('teamId')) {
        obj['teamId'] = ApiClient.convertToType(data['teamId'], 'String');
      }
      if (data.hasOwnProperty('userRecId')) {
        obj['userRecId'] = ApiClient.convertToType(data['userRecId'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} isTeamManager
   */
  exports.prototype['isTeamManager'] = undefined;
  /**
   * @member {Boolean} setAsDefaultTeam
   */
  exports.prototype['setAsDefaultTeam'] = undefined;
  /**
   * @member {String} teamId
   */
  exports.prototype['teamId'] = undefined;
  /**
   * @member {String} userRecId
   */
  exports.prototype['userRecId'] = undefined;



  return exports;
}));


