/**
 * Cherwell Rest API
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CherwellRestApi) {
      root.CherwellRestApi = {};
    }
    root.CherwellRestApi.SaveApiClientSettingRequest = factory(root.CherwellRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SaveApiClientSettingRequest model module.
   * @module model/SaveApiClientSettingRequest
   * @version 9.2.0
   */

  /**
   * Constructs a new <code>SaveApiClientSettingRequest</code>.
   * @alias module:model/SaveApiClientSettingRequest
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>SaveApiClientSettingRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SaveApiClientSettingRequest} obj Optional instance to populate.
   * @return {module:model/SaveApiClientSettingRequest} The populated <code>SaveApiClientSettingRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('allowAnonymousAccess')) {
        obj['allowAnonymousAccess'] = ApiClient.convertToType(data['allowAnonymousAccess'], 'Boolean');
      }
      if (data.hasOwnProperty('apiAccessIsEnabled')) {
        obj['apiAccessIsEnabled'] = ApiClient.convertToType(data['apiAccessIsEnabled'], 'Boolean');
      }
      if (data.hasOwnProperty('createNewClientKey')) {
        obj['createNewClientKey'] = ApiClient.convertToType(data['createNewClientKey'], 'Boolean');
      }
      if (data.hasOwnProperty('culture')) {
        obj['culture'] = ApiClient.convertToType(data['culture'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('refreshTokenLifespanMinutes')) {
        obj['refreshTokenLifespanMinutes'] = ApiClient.convertToType(data['refreshTokenLifespanMinutes'], 'Number');
      }
      if (data.hasOwnProperty('standInKey')) {
        obj['standInKey'] = ApiClient.convertToType(data['standInKey'], 'String');
      }
      if (data.hasOwnProperty('tokenLifespanMinutes')) {
        obj['tokenLifespanMinutes'] = ApiClient.convertToType(data['tokenLifespanMinutes'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} allowAnonymousAccess
   */
  exports.prototype['allowAnonymousAccess'] = undefined;
  /**
   * @member {Boolean} apiAccessIsEnabled
   */
  exports.prototype['apiAccessIsEnabled'] = undefined;
  /**
   * @member {Boolean} createNewClientKey
   */
  exports.prototype['createNewClientKey'] = undefined;
  /**
   * @member {String} culture
   */
  exports.prototype['culture'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Number} refreshTokenLifespanMinutes
   */
  exports.prototype['refreshTokenLifespanMinutes'] = undefined;
  /**
   * @member {String} standInKey
   */
  exports.prototype['standInKey'] = undefined;
  /**
   * @member {Number} tokenLifespanMinutes
   */
  exports.prototype['tokenLifespanMinutes'] = undefined;



  return exports;
}));


