/**
 * Cherwell Rest API
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Link', 'model/SearchFolder', 'model/SearchItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Link'), require('./SearchFolder'), require('./SearchItem'));
  } else {
    // Browser globals (root is window)
    if (!root.CherwellRestApi) {
      root.CherwellRestApi = {};
    }
    root.CherwellRestApi.SearchFolder = factory(root.CherwellRestApi.ApiClient, root.CherwellRestApi.Link, root.CherwellRestApi.SearchFolder, root.CherwellRestApi.SearchItem);
  }
}(this, function(ApiClient, Link, SearchFolder, SearchItem) {
  'use strict';




  /**
   * The SearchFolder model module.
   * @module model/SearchFolder
   * @version 9.2.0
   */

  /**
   * Constructs a new <code>SearchFolder</code>.
   * @alias module:model/SearchFolder
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>SearchFolder</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchFolder} obj Optional instance to populate.
   * @return {module:model/SearchFolder} The populated <code>SearchFolder</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('association')) {
        obj['association'] = ApiClient.convertToType(data['association'], 'String');
      }
      if (data.hasOwnProperty('childFolders')) {
        obj['childFolders'] = ApiClient.convertToType(data['childFolders'], [SearchFolder]);
      }
      if (data.hasOwnProperty('childItems')) {
        obj['childItems'] = ApiClient.convertToType(data['childItems'], [SearchItem]);
      }
      if (data.hasOwnProperty('folderId')) {
        obj['folderId'] = ApiClient.convertToType(data['folderId'], 'String');
      }
      if (data.hasOwnProperty('folderName')) {
        obj['folderName'] = ApiClient.convertToType(data['folderName'], 'String');
      }
      if (data.hasOwnProperty('links')) {
        obj['links'] = ApiClient.convertToType(data['links'], [Link]);
      }
      if (data.hasOwnProperty('localizedScopeName')) {
        obj['localizedScopeName'] = ApiClient.convertToType(data['localizedScopeName'], 'String');
      }
      if (data.hasOwnProperty('parentFolderId')) {
        obj['parentFolderId'] = ApiClient.convertToType(data['parentFolderId'], 'String');
      }
      if (data.hasOwnProperty('scope')) {
        obj['scope'] = ApiClient.convertToType(data['scope'], 'String');
      }
      if (data.hasOwnProperty('scopeOwner')) {
        obj['scopeOwner'] = ApiClient.convertToType(data['scopeOwner'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} association
   */
  exports.prototype['association'] = undefined;
  /**
   * @member {Array.<module:model/SearchFolder>} childFolders
   */
  exports.prototype['childFolders'] = undefined;
  /**
   * @member {Array.<module:model/SearchItem>} childItems
   */
  exports.prototype['childItems'] = undefined;
  /**
   * @member {String} folderId
   */
  exports.prototype['folderId'] = undefined;
  /**
   * @member {String} folderName
   */
  exports.prototype['folderName'] = undefined;
  /**
   * @member {Array.<module:model/Link>} links
   */
  exports.prototype['links'] = undefined;
  /**
   * @member {String} localizedScopeName
   */
  exports.prototype['localizedScopeName'] = undefined;
  /**
   * @member {String} parentFolderId
   */
  exports.prototype['parentFolderId'] = undefined;
  /**
   * @member {String} scope
   */
  exports.prototype['scope'] = undefined;
  /**
   * @member {String} scopeOwner
   */
  exports.prototype['scopeOwner'] = undefined;



  return exports;
}));


