/**
 * Cherwell Rest API
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CherwellRestApi) {
      root.CherwellRestApi = {};
    }
    root.CherwellRestApi.TemplateRequest = factory(root.CherwellRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The TemplateRequest model module.
   * @module model/TemplateRequest
   * @version 9.2.0
   */

  /**
   * Constructs a new <code>TemplateRequest</code>.
   * @alias module:model/TemplateRequest
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>TemplateRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TemplateRequest} obj Optional instance to populate.
   * @return {module:model/TemplateRequest} The populated <code>TemplateRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('busObId')) {
        obj['busObId'] = ApiClient.convertToType(data['busObId'], 'String');
      }
      if (data.hasOwnProperty('fieldNames')) {
        obj['fieldNames'] = ApiClient.convertToType(data['fieldNames'], ['String']);
      }
      if (data.hasOwnProperty('fieldIds')) {
        obj['fieldIds'] = ApiClient.convertToType(data['fieldIds'], ['String']);
      }
      if (data.hasOwnProperty('includeAll')) {
        obj['includeAll'] = ApiClient.convertToType(data['includeAll'], 'Boolean');
      }
      if (data.hasOwnProperty('includeRequired')) {
        obj['includeRequired'] = ApiClient.convertToType(data['includeRequired'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {String} busObId
   */
  exports.prototype['busObId'] = undefined;
  /**
   * @member {Array.<String>} fieldNames
   */
  exports.prototype['fieldNames'] = undefined;
  /**
   * @member {Array.<String>} fieldIds
   */
  exports.prototype['fieldIds'] = undefined;
  /**
   * @member {Boolean} includeAll
   */
  exports.prototype['includeAll'] = undefined;
  /**
   * @member {Boolean} includeRequired
   */
  exports.prototype['includeRequired'] = undefined;



  return exports;
}));


