/**
 * Cherwell Rest API
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FieldTemplateItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FieldTemplateItem'));
  } else {
    // Browser globals (root is window)
    if (!root.CherwellRestApi) {
      root.CherwellRestApi = {};
    }
    root.CherwellRestApi.UserSaveV2Request = factory(root.CherwellRestApi.ApiClient, root.CherwellRestApi.FieldTemplateItem);
  }
}(this, function(ApiClient, FieldTemplateItem) {
  'use strict';




  /**
   * The UserSaveV2Request model module.
   * @module model/UserSaveV2Request
   * @version 9.2.0
   */

  /**
   * Constructs a new <code>UserSaveV2Request</code>.
   * @alias module:model/UserSaveV2Request
   * @class
   */
  var exports = function() {
    var _this = this;


















  };

  /**
   * Constructs a <code>UserSaveV2Request</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserSaveV2Request} obj Optional instance to populate.
   * @return {module:model/UserSaveV2Request} The populated <code>UserSaveV2Request</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('accountLocked')) {
        obj['accountLocked'] = ApiClient.convertToType(data['accountLocked'], 'Boolean');
      }
      if (data.hasOwnProperty('allCultures')) {
        obj['allCultures'] = ApiClient.convertToType(data['allCultures'], 'Boolean');
      }
      if (data.hasOwnProperty('busObId')) {
        obj['busObId'] = ApiClient.convertToType(data['busObId'], 'String');
      }
      if (data.hasOwnProperty('busObPublicId')) {
        obj['busObPublicId'] = ApiClient.convertToType(data['busObPublicId'], 'String');
      }
      if (data.hasOwnProperty('busObRecId')) {
        obj['busObRecId'] = ApiClient.convertToType(data['busObRecId'], 'String');
      }
      if (data.hasOwnProperty('displayName')) {
        obj['displayName'] = ApiClient.convertToType(data['displayName'], 'String');
      }
      if (data.hasOwnProperty('ldapRequired')) {
        obj['ldapRequired'] = ApiClient.convertToType(data['ldapRequired'], 'Boolean');
      }
      if (data.hasOwnProperty('loginId')) {
        obj['loginId'] = ApiClient.convertToType(data['loginId'], 'String');
      }
      if (data.hasOwnProperty('nextPasswordResetDate')) {
        obj['nextPasswordResetDate'] = ApiClient.convertToType(data['nextPasswordResetDate'], 'Date');
      }
      if (data.hasOwnProperty('password')) {
        obj['password'] = ApiClient.convertToType(data['password'], 'String');
      }
      if (data.hasOwnProperty('passwordNeverExpires')) {
        obj['passwordNeverExpires'] = ApiClient.convertToType(data['passwordNeverExpires'], 'Boolean');
      }
      if (data.hasOwnProperty('securityGroupId')) {
        obj['securityGroupId'] = ApiClient.convertToType(data['securityGroupId'], 'String');
      }
      if (data.hasOwnProperty('specificCulture')) {
        obj['specificCulture'] = ApiClient.convertToType(data['specificCulture'], 'String');
      }
      if (data.hasOwnProperty('userCannotChangePassword')) {
        obj['userCannotChangePassword'] = ApiClient.convertToType(data['userCannotChangePassword'], 'Boolean');
      }
      if (data.hasOwnProperty('userInfoFields')) {
        obj['userInfoFields'] = ApiClient.convertToType(data['userInfoFields'], [FieldTemplateItem]);
      }
      if (data.hasOwnProperty('userMustChangePasswordAtNextLogin')) {
        obj['userMustChangePasswordAtNextLogin'] = ApiClient.convertToType(data['userMustChangePasswordAtNextLogin'], 'Boolean');
      }
      if (data.hasOwnProperty('windowsUserId')) {
        obj['windowsUserId'] = ApiClient.convertToType(data['windowsUserId'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} accountLocked
   */
  exports.prototype['accountLocked'] = undefined;
  /**
   * @member {Boolean} allCultures
   */
  exports.prototype['allCultures'] = undefined;
  /**
   * @member {String} busObId
   */
  exports.prototype['busObId'] = undefined;
  /**
   * @member {String} busObPublicId
   */
  exports.prototype['busObPublicId'] = undefined;
  /**
   * @member {String} busObRecId
   */
  exports.prototype['busObRecId'] = undefined;
  /**
   * @member {String} displayName
   */
  exports.prototype['displayName'] = undefined;
  /**
   * @member {Boolean} ldapRequired
   */
  exports.prototype['ldapRequired'] = undefined;
  /**
   * @member {String} loginId
   */
  exports.prototype['loginId'] = undefined;
  /**
   * @member {Date} nextPasswordResetDate
   */
  exports.prototype['nextPasswordResetDate'] = undefined;
  /**
   * @member {String} password
   */
  exports.prototype['password'] = undefined;
  /**
   * @member {Boolean} passwordNeverExpires
   */
  exports.prototype['passwordNeverExpires'] = undefined;
  /**
   * @member {String} securityGroupId
   */
  exports.prototype['securityGroupId'] = undefined;
  /**
   * @member {String} specificCulture
   */
  exports.prototype['specificCulture'] = undefined;
  /**
   * @member {Boolean} userCannotChangePassword
   */
  exports.prototype['userCannotChangePassword'] = undefined;
  /**
   * @member {Array.<module:model/FieldTemplateItem>} userInfoFields
   */
  exports.prototype['userInfoFields'] = undefined;
  /**
   * @member {Boolean} userMustChangePasswordAtNextLogin
   */
  exports.prototype['userMustChangePasswordAtNextLogin'] = undefined;
  /**
   * @member {String} windowsUserId
   */
  exports.prototype['windowsUserId'] = undefined;



  return exports;
}));


