/**
 * Cherwell Rest API
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CherwellRestApi);
  }
}(this, function(expect, CherwellRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CherwellRestApi.Attachment();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Attachment', function() {
    it('should create an instance of Attachment', function() {
      // uncomment below and update the code to test Attachment
      //var instance = new CherwellRestApi.Attachment();
      //expect(instance).to.be.a(CherwellRestApi.Attachment);
    });

    it('should have the property attachedBusObId (base name: "attachedBusObId")', function() {
      // uncomment below and update the code to test the property attachedBusObId
      //var instance = new CherwellRestApi.Attachment();
      //expect(instance).to.be();
    });

    it('should have the property attachedBusObRecId (base name: "attachedBusObRecId")', function() {
      // uncomment below and update the code to test the property attachedBusObRecId
      //var instance = new CherwellRestApi.Attachment();
      //expect(instance).to.be();
    });

    it('should have the property attachmentFileId (base name: "attachmentFileId")', function() {
      // uncomment below and update the code to test the property attachmentFileId
      //var instance = new CherwellRestApi.Attachment();
      //expect(instance).to.be();
    });

    it('should have the property attachmentFileName (base name: "attachmentFileName")', function() {
      // uncomment below and update the code to test the property attachmentFileName
      //var instance = new CherwellRestApi.Attachment();
      //expect(instance).to.be();
    });

    it('should have the property attachmentFileType (base name: "attachmentFileType")', function() {
      // uncomment below and update the code to test the property attachmentFileType
      //var instance = new CherwellRestApi.Attachment();
      //expect(instance).to.be();
    });

    it('should have the property attachmentId (base name: "attachmentId")', function() {
      // uncomment below and update the code to test the property attachmentId
      //var instance = new CherwellRestApi.Attachment();
      //expect(instance).to.be();
    });

    it('should have the property attachmentType (base name: "attachmentType")', function() {
      // uncomment below and update the code to test the property attachmentType
      //var instance = new CherwellRestApi.Attachment();
      //expect(instance).to.be();
    });

    it('should have the property busObId (base name: "busObId")', function() {
      // uncomment below and update the code to test the property busObId
      //var instance = new CherwellRestApi.Attachment();
      //expect(instance).to.be();
    });

    it('should have the property busObRecId (base name: "busObRecId")', function() {
      // uncomment below and update the code to test the property busObRecId
      //var instance = new CherwellRestApi.Attachment();
      //expect(instance).to.be();
    });

    it('should have the property comment (base name: "comment")', function() {
      // uncomment below and update the code to test the property comment
      //var instance = new CherwellRestApi.Attachment();
      //expect(instance).to.be();
    });

    it('should have the property created (base name: "created")', function() {
      // uncomment below and update the code to test the property created
      //var instance = new CherwellRestApi.Attachment();
      //expect(instance).to.be();
    });

    it('should have the property displayText (base name: "displayText")', function() {
      // uncomment below and update the code to test the property displayText
      //var instance = new CherwellRestApi.Attachment();
      //expect(instance).to.be();
    });

    it('should have the property links (base name: "links")', function() {
      // uncomment below and update the code to test the property links
      //var instance = new CherwellRestApi.Attachment();
      //expect(instance).to.be();
    });

    it('should have the property owner (base name: "owner")', function() {
      // uncomment below and update the code to test the property owner
      //var instance = new CherwellRestApi.Attachment();
      //expect(instance).to.be();
    });

    it('should have the property scope (base name: "scope")', function() {
      // uncomment below and update the code to test the property scope
      //var instance = new CherwellRestApi.Attachment();
      //expect(instance).to.be();
    });

    it('should have the property scopeOwner (base name: "scopeOwner")', function() {
      // uncomment below and update the code to test the property scopeOwner
      //var instance = new CherwellRestApi.Attachment();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new CherwellRestApi.Attachment();
      //expect(instance).to.be();
    });

  });

}));
