/**
 * Cherwell Rest API
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CherwellRestApi);
  }
}(this, function(expect, CherwellRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CherwellRestApi.BusinessObjectPermission();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BusinessObjectPermission', function() {
    it('should create an instance of BusinessObjectPermission', function() {
      // uncomment below and update the code to test BusinessObjectPermission
      //var instance = new CherwellRestApi.BusinessObjectPermission();
      //expect(instance).to.be.a(CherwellRestApi.BusinessObjectPermission);
    });

    it('should have the property busObId (base name: "busObId")', function() {
      // uncomment below and update the code to test the property busObId
      //var instance = new CherwellRestApi.BusinessObjectPermission();
      //expect(instance).to.be();
    });

    it('should have the property busObName (base name: "busObName")', function() {
      // uncomment below and update the code to test the property busObName
      //var instance = new CherwellRestApi.BusinessObjectPermission();
      //expect(instance).to.be();
    });

    it('should have the property departmentMemberEdit (base name: "departmentMemberEdit")', function() {
      // uncomment below and update the code to test the property departmentMemberEdit
      //var instance = new CherwellRestApi.BusinessObjectPermission();
      //expect(instance).to.be();
    });

    it('should have the property departmentMemberView (base name: "departmentMemberView")', function() {
      // uncomment below and update the code to test the property departmentMemberView
      //var instance = new CherwellRestApi.BusinessObjectPermission();
      //expect(instance).to.be();
    });

    it('should have the property edit (base name: "edit")', function() {
      // uncomment below and update the code to test the property edit
      //var instance = new CherwellRestApi.BusinessObjectPermission();
      //expect(instance).to.be();
    });

    it('should have the property fieldPermissions (base name: "fieldPermissions")', function() {
      // uncomment below and update the code to test the property fieldPermissions
      //var instance = new CherwellRestApi.BusinessObjectPermission();
      //expect(instance).to.be();
    });

    it('should have the property managerOfOwnerEdit (base name: "managerOfOwnerEdit")', function() {
      // uncomment below and update the code to test the property managerOfOwnerEdit
      //var instance = new CherwellRestApi.BusinessObjectPermission();
      //expect(instance).to.be();
    });

    it('should have the property managerOfOwnerView (base name: "managerOfOwnerView")', function() {
      // uncomment below and update the code to test the property managerOfOwnerView
      //var instance = new CherwellRestApi.BusinessObjectPermission();
      //expect(instance).to.be();
    });

    it('should have the property ownerEdit (base name: "ownerEdit")', function() {
      // uncomment below and update the code to test the property ownerEdit
      //var instance = new CherwellRestApi.BusinessObjectPermission();
      //expect(instance).to.be();
    });

    it('should have the property ownerView (base name: "ownerView")', function() {
      // uncomment below and update the code to test the property ownerView
      //var instance = new CherwellRestApi.BusinessObjectPermission();
      //expect(instance).to.be();
    });

    it('should have the property teamEdit (base name: "teamEdit")', function() {
      // uncomment below and update the code to test the property teamEdit
      //var instance = new CherwellRestApi.BusinessObjectPermission();
      //expect(instance).to.be();
    });

    it('should have the property teamManagerOfOwnerEdit (base name: "teamManagerOfOwnerEdit")', function() {
      // uncomment below and update the code to test the property teamManagerOfOwnerEdit
      //var instance = new CherwellRestApi.BusinessObjectPermission();
      //expect(instance).to.be();
    });

    it('should have the property teamManagerOfOwnerView (base name: "teamManagerOfOwnerView")', function() {
      // uncomment below and update the code to test the property teamManagerOfOwnerView
      //var instance = new CherwellRestApi.BusinessObjectPermission();
      //expect(instance).to.be();
    });

    it('should have the property teamView (base name: "teamView")', function() {
      // uncomment below and update the code to test the property teamView
      //var instance = new CherwellRestApi.BusinessObjectPermission();
      //expect(instance).to.be();
    });

    it('should have the property view (base name: "view")', function() {
      // uncomment below and update the code to test the property view
      //var instance = new CherwellRestApi.BusinessObjectPermission();
      //expect(instance).to.be();
    });

  });

}));
