/**
 * Cherwell Rest API
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CherwellRestApi);
  }
}(this, function(expect, CherwellRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CherwellRestApi.NameValuePair();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NameValuePair', function() {
    it('should create an instance of NameValuePair', function() {
      // uncomment below and update the code to test NameValuePair
      //var instance = new CherwellRestApi.NameValuePair();
      //expect(instance).to.be.a(CherwellRestApi.NameValuePair);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new CherwellRestApi.NameValuePair();
      //expect(instance).to.be();
    });

    it('should have the property valueObject (base name: "valueObject")', function() {
      // uncomment below and update the code to test the property valueObject
      //var instance = new CherwellRestApi.NameValuePair();
      //expect(instance).to.be();
    });

    it('should have the property valueString (base name: "valueString")', function() {
      // uncomment below and update the code to test the property valueString
      //var instance = new CherwellRestApi.NameValuePair();
      //expect(instance).to.be();
    });

    it('should have the property category (base name: "category")', function() {
      // uncomment below and update the code to test the property category
      //var instance = new CherwellRestApi.NameValuePair();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new CherwellRestApi.NameValuePair();
      //expect(instance).to.be();
    });

    it('should have the property displayShowsValue (base name: "displayShowsValue")', function() {
      // uncomment below and update the code to test the property displayShowsValue
      //var instance = new CherwellRestApi.NameValuePair();
      //expect(instance).to.be();
    });

    it('should have the property specialUseFlag (base name: "specialUseFlag")', function() {
      // uncomment below and update the code to test the property specialUseFlag
      //var instance = new CherwellRestApi.NameValuePair();
      //expect(instance).to.be();
    });

    it('should have the property displayString (base name: "displayString")', function() {
      // uncomment below and update the code to test the property displayString
      //var instance = new CherwellRestApi.NameValuePair();
      //expect(instance).to.be();
    });

  });

}));
