/**
 * Cherwell Rest API
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CherwellRestApi);
  }
}(this, function(expect, CherwellRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CherwellRestApi.RelatedBusinessObjectResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RelatedBusinessObjectResponse', function() {
    it('should create an instance of RelatedBusinessObjectResponse', function() {
      // uncomment below and update the code to test RelatedBusinessObjectResponse
      //var instance = new CherwellRestApi.RelatedBusinessObjectResponse();
      //expect(instance).to.be.a(CherwellRestApi.RelatedBusinessObjectResponse);
    });

    it('should have the property errorCode (base name: "errorCode")', function() {
      // uncomment below and update the code to test the property errorCode
      //var instance = new CherwellRestApi.RelatedBusinessObjectResponse();
      //expect(instance).to.be();
    });

    it('should have the property errorMessage (base name: "errorMessage")', function() {
      // uncomment below and update the code to test the property errorMessage
      //var instance = new CherwellRestApi.RelatedBusinessObjectResponse();
      //expect(instance).to.be();
    });

    it('should have the property hasError (base name: "hasError")', function() {
      // uncomment below and update the code to test the property hasError
      //var instance = new CherwellRestApi.RelatedBusinessObjectResponse();
      //expect(instance).to.be();
    });

    it('should have the property links (base name: "links")', function() {
      // uncomment below and update the code to test the property links
      //var instance = new CherwellRestApi.RelatedBusinessObjectResponse();
      //expect(instance).to.be();
    });

    it('should have the property pageNumber (base name: "pageNumber")', function() {
      // uncomment below and update the code to test the property pageNumber
      //var instance = new CherwellRestApi.RelatedBusinessObjectResponse();
      //expect(instance).to.be();
    });

    it('should have the property pageSize (base name: "pageSize")', function() {
      // uncomment below and update the code to test the property pageSize
      //var instance = new CherwellRestApi.RelatedBusinessObjectResponse();
      //expect(instance).to.be();
    });

    it('should have the property parentBusObId (base name: "parentBusObId")', function() {
      // uncomment below and update the code to test the property parentBusObId
      //var instance = new CherwellRestApi.RelatedBusinessObjectResponse();
      //expect(instance).to.be();
    });

    it('should have the property parentBusObPublicId (base name: "parentBusObPublicId")', function() {
      // uncomment below and update the code to test the property parentBusObPublicId
      //var instance = new CherwellRestApi.RelatedBusinessObjectResponse();
      //expect(instance).to.be();
    });

    it('should have the property parentBusObRecId (base name: "parentBusObRecId")', function() {
      // uncomment below and update the code to test the property parentBusObRecId
      //var instance = new CherwellRestApi.RelatedBusinessObjectResponse();
      //expect(instance).to.be();
    });

    it('should have the property relatedBusinessObjects (base name: "relatedBusinessObjects")', function() {
      // uncomment below and update the code to test the property relatedBusinessObjects
      //var instance = new CherwellRestApi.RelatedBusinessObjectResponse();
      //expect(instance).to.be();
    });

    it('should have the property relationshipId (base name: "relationshipId")', function() {
      // uncomment below and update the code to test the property relationshipId
      //var instance = new CherwellRestApi.RelatedBusinessObjectResponse();
      //expect(instance).to.be();
    });

    it('should have the property totalRecords (base name: "totalRecords")', function() {
      // uncomment below and update the code to test the property totalRecords
      //var instance = new CherwellRestApi.RelatedBusinessObjectResponse();
      //expect(instance).to.be();
    });

  });

}));
