/**
 * Cherwell Rest API
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CherwellRestApi);
  }
}(this, function(expect, CherwellRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CherwellRestApi.RelatedBusinessObjectRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RelatedBusinessObjectRequest', function() {
    it('should create an instance of RelatedBusinessObjectRequest', function() {
      // uncomment below and update the code to test RelatedBusinessObjectRequest
      //var instance = new CherwellRestApi.RelatedBusinessObjectRequest();
      //expect(instance).to.be.a(CherwellRestApi.RelatedBusinessObjectRequest);
    });

    it('should have the property allFields (base name: "allFields")', function() {
      // uncomment below and update the code to test the property allFields
      //var instance = new CherwellRestApi.RelatedBusinessObjectRequest();
      //expect(instance).to.be();
    });

    it('should have the property customGridId (base name: "customGridId")', function() {
      // uncomment below and update the code to test the property customGridId
      //var instance = new CherwellRestApi.RelatedBusinessObjectRequest();
      //expect(instance).to.be();
    });

    it('should have the property fieldsList (base name: "fieldsList")', function() {
      // uncomment below and update the code to test the property fieldsList
      //var instance = new CherwellRestApi.RelatedBusinessObjectRequest();
      //expect(instance).to.be();
    });

    it('should have the property filters (base name: "filters")', function() {
      // uncomment below and update the code to test the property filters
      //var instance = new CherwellRestApi.RelatedBusinessObjectRequest();
      //expect(instance).to.be();
    });

    it('should have the property pageNumber (base name: "pageNumber")', function() {
      // uncomment below and update the code to test the property pageNumber
      //var instance = new CherwellRestApi.RelatedBusinessObjectRequest();
      //expect(instance).to.be();
    });

    it('should have the property pageSize (base name: "pageSize")', function() {
      // uncomment below and update the code to test the property pageSize
      //var instance = new CherwellRestApi.RelatedBusinessObjectRequest();
      //expect(instance).to.be();
    });

    it('should have the property parentBusObId (base name: "parentBusObId")', function() {
      // uncomment below and update the code to test the property parentBusObId
      //var instance = new CherwellRestApi.RelatedBusinessObjectRequest();
      //expect(instance).to.be();
    });

    it('should have the property parentBusObRecId (base name: "parentBusObRecId")', function() {
      // uncomment below and update the code to test the property parentBusObRecId
      //var instance = new CherwellRestApi.RelatedBusinessObjectRequest();
      //expect(instance).to.be();
    });

    it('should have the property relationshipId (base name: "relationshipId")', function() {
      // uncomment below and update the code to test the property relationshipId
      //var instance = new CherwellRestApi.RelatedBusinessObjectRequest();
      //expect(instance).to.be();
    });

    it('should have the property sorting (base name: "sorting")', function() {
      // uncomment below and update the code to test the property sorting
      //var instance = new CherwellRestApi.RelatedBusinessObjectRequest();
      //expect(instance).to.be();
    });

    it('should have the property useDefaultGrid (base name: "useDefaultGrid")', function() {
      // uncomment below and update the code to test the property useDefaultGrid
      //var instance = new CherwellRestApi.RelatedBusinessObjectRequest();
      //expect(instance).to.be();
    });

  });

}));
