/**
 * Cherwell Rest API
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CherwellRestApi);
  }
}(this, function(expect, CherwellRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CherwellRestApi.SearchResultsRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SearchResultsRequest', function() {
    it('should create an instance of SearchResultsRequest', function() {
      // uncomment below and update the code to test SearchResultsRequest
      //var instance = new CherwellRestApi.SearchResultsRequest();
      //expect(instance).to.be.a(CherwellRestApi.SearchResultsRequest);
    });

    it('should have the property association (base name: "association")', function() {
      // uncomment below and update the code to test the property association
      //var instance = new CherwellRestApi.SearchResultsRequest();
      //expect(instance).to.be();
    });

    it('should have the property busObId (base name: "busObId")', function() {
      // uncomment below and update the code to test the property busObId
      //var instance = new CherwellRestApi.SearchResultsRequest();
      //expect(instance).to.be();
    });

    it('should have the property customGridDefId (base name: "customGridDefId")', function() {
      // uncomment below and update the code to test the property customGridDefId
      //var instance = new CherwellRestApi.SearchResultsRequest();
      //expect(instance).to.be();
    });

    it('should have the property dateTimeFormatting (base name: "dateTimeFormatting")', function() {
      // uncomment below and update the code to test the property dateTimeFormatting
      //var instance = new CherwellRestApi.SearchResultsRequest();
      //expect(instance).to.be();
    });

    it('should have the property fieldId (base name: "fieldId")', function() {
      // uncomment below and update the code to test the property fieldId
      //var instance = new CherwellRestApi.SearchResultsRequest();
      //expect(instance).to.be();
    });

    it('should have the property fields (base name: "fields")', function() {
      // uncomment below and update the code to test the property fields
      //var instance = new CherwellRestApi.SearchResultsRequest();
      //expect(instance).to.be();
    });

    it('should have the property filters (base name: "filters")', function() {
      // uncomment below and update the code to test the property filters
      //var instance = new CherwellRestApi.SearchResultsRequest();
      //expect(instance).to.be();
    });

    it('should have the property includeAllFields (base name: "includeAllFields")', function() {
      // uncomment below and update the code to test the property includeAllFields
      //var instance = new CherwellRestApi.SearchResultsRequest();
      //expect(instance).to.be();
    });

    it('should have the property includeSchema (base name: "includeSchema")', function() {
      // uncomment below and update the code to test the property includeSchema
      //var instance = new CherwellRestApi.SearchResultsRequest();
      //expect(instance).to.be();
    });

    it('should have the property pageNumber (base name: "pageNumber")', function() {
      // uncomment below and update the code to test the property pageNumber
      //var instance = new CherwellRestApi.SearchResultsRequest();
      //expect(instance).to.be();
    });

    it('should have the property pageSize (base name: "pageSize")', function() {
      // uncomment below and update the code to test the property pageSize
      //var instance = new CherwellRestApi.SearchResultsRequest();
      //expect(instance).to.be();
    });

    it('should have the property scope (base name: "scope")', function() {
      // uncomment below and update the code to test the property scope
      //var instance = new CherwellRestApi.SearchResultsRequest();
      //expect(instance).to.be();
    });

    it('should have the property scopeOwner (base name: "scopeOwner")', function() {
      // uncomment below and update the code to test the property scopeOwner
      //var instance = new CherwellRestApi.SearchResultsRequest();
      //expect(instance).to.be();
    });

    it('should have the property searchId (base name: "searchId")', function() {
      // uncomment below and update the code to test the property searchId
      //var instance = new CherwellRestApi.SearchResultsRequest();
      //expect(instance).to.be();
    });

    it('should have the property searchName (base name: "searchName")', function() {
      // uncomment below and update the code to test the property searchName
      //var instance = new CherwellRestApi.SearchResultsRequest();
      //expect(instance).to.be();
    });

    it('should have the property searchText (base name: "searchText")', function() {
      // uncomment below and update the code to test the property searchText
      //var instance = new CherwellRestApi.SearchResultsRequest();
      //expect(instance).to.be();
    });

    it('should have the property sorting (base name: "sorting")', function() {
      // uncomment below and update the code to test the property sorting
      //var instance = new CherwellRestApi.SearchResultsRequest();
      //expect(instance).to.be();
    });

    it('should have the property promptValues (base name: "promptValues")', function() {
      // uncomment below and update the code to test the property promptValues
      //var instance = new CherwellRestApi.SearchResultsRequest();
      //expect(instance).to.be();
    });

  });

}));
