/**
 * Cherwell Rest API
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CherwellRestApi);
  }
}(this, function(expect, CherwellRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CherwellRestApi.SecurityApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SecurityApi', function() {
    describe('securityGetClientSecuritySettingsV1', function() {
      it('should call securityGetClientSecuritySettingsV1 successfully', function(done) {
        //uncomment below and update the code to test securityGetClientSecuritySettingsV1
        //instance.securityGetClientSecuritySettingsV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityGetRolesV1', function() {
      it('should call securityGetRolesV1 successfully', function(done) {
        //uncomment below and update the code to test securityGetRolesV1
        //instance.securityGetRolesV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityGetRolesV2', function() {
      it('should call securityGetRolesV2 successfully', function(done) {
        //uncomment below and update the code to test securityGetRolesV2
        //instance.securityGetRolesV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityGetSecurityGroupBusinessObjectPermissionsByBusObIdV1', function() {
      it('should call securityGetSecurityGroupBusinessObjectPermissionsByBusObIdV1 successfully', function(done) {
        //uncomment below and update the code to test securityGetSecurityGroupBusinessObjectPermissionsByBusObIdV1
        //instance.securityGetSecurityGroupBusinessObjectPermissionsByBusObIdV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityGetSecurityGroupBusinessObjectPermissionsByBusObIdV2', function() {
      it('should call securityGetSecurityGroupBusinessObjectPermissionsByBusObIdV2 successfully', function(done) {
        //uncomment below and update the code to test securityGetSecurityGroupBusinessObjectPermissionsByBusObIdV2
        //instance.securityGetSecurityGroupBusinessObjectPermissionsByBusObIdV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityGetSecurityGroupBusinessObjectPermissionsByBusObNameV1', function() {
      it('should call securityGetSecurityGroupBusinessObjectPermissionsByBusObNameV1 successfully', function(done) {
        //uncomment below and update the code to test securityGetSecurityGroupBusinessObjectPermissionsByBusObNameV1
        //instance.securityGetSecurityGroupBusinessObjectPermissionsByBusObNameV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityGetSecurityGroupBusinessObjectPermissionsByBusObNameV2', function() {
      it('should call securityGetSecurityGroupBusinessObjectPermissionsByBusObNameV2 successfully', function(done) {
        //uncomment below and update the code to test securityGetSecurityGroupBusinessObjectPermissionsByBusObNameV2
        //instance.securityGetSecurityGroupBusinessObjectPermissionsByBusObNameV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityGetSecurityGroupBusinessObjectPermissionsForCurrentUserByBusObIdV1', function() {
      it('should call securityGetSecurityGroupBusinessObjectPermissionsForCurrentUserByBusObIdV1 successfully', function(done) {
        //uncomment below and update the code to test securityGetSecurityGroupBusinessObjectPermissionsForCurrentUserByBusObIdV1
        //instance.securityGetSecurityGroupBusinessObjectPermissionsForCurrentUserByBusObIdV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityGetSecurityGroupBusinessObjectPermissionsForCurrentUserByBusObIdV2', function() {
      it('should call securityGetSecurityGroupBusinessObjectPermissionsForCurrentUserByBusObIdV2 successfully', function(done) {
        //uncomment below and update the code to test securityGetSecurityGroupBusinessObjectPermissionsForCurrentUserByBusObIdV2
        //instance.securityGetSecurityGroupBusinessObjectPermissionsForCurrentUserByBusObIdV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityGetSecurityGroupBusinessObjectPermissionsForCurrentUserByBusObNameV1', function() {
      it('should call securityGetSecurityGroupBusinessObjectPermissionsForCurrentUserByBusObNameV1 successfully', function(done) {
        //uncomment below and update the code to test securityGetSecurityGroupBusinessObjectPermissionsForCurrentUserByBusObNameV1
        //instance.securityGetSecurityGroupBusinessObjectPermissionsForCurrentUserByBusObNameV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityGetSecurityGroupBusinessObjectPermissionsForCurrentUserByBusObNameV2', function() {
      it('should call securityGetSecurityGroupBusinessObjectPermissionsForCurrentUserByBusObNameV2 successfully', function(done) {
        //uncomment below and update the code to test securityGetSecurityGroupBusinessObjectPermissionsForCurrentUserByBusObNameV2
        //instance.securityGetSecurityGroupBusinessObjectPermissionsForCurrentUserByBusObNameV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityGetSecurityGroupCategoriesV1', function() {
      it('should call securityGetSecurityGroupCategoriesV1 successfully', function(done) {
        //uncomment below and update the code to test securityGetSecurityGroupCategoriesV1
        //instance.securityGetSecurityGroupCategoriesV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityGetSecurityGroupCategoriesV2', function() {
      it('should call securityGetSecurityGroupCategoriesV2 successfully', function(done) {
        //uncomment below and update the code to test securityGetSecurityGroupCategoriesV2
        //instance.securityGetSecurityGroupCategoriesV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityGetSecurityGroupRightsByGroupIdAndCategoryIdV1', function() {
      it('should call securityGetSecurityGroupRightsByGroupIdAndCategoryIdV1 successfully', function(done) {
        //uncomment below and update the code to test securityGetSecurityGroupRightsByGroupIdAndCategoryIdV1
        //instance.securityGetSecurityGroupRightsByGroupIdAndCategoryIdV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityGetSecurityGroupRightsByGroupIdAndCategoryIdV2', function() {
      it('should call securityGetSecurityGroupRightsByGroupIdAndCategoryIdV2 successfully', function(done) {
        //uncomment below and update the code to test securityGetSecurityGroupRightsByGroupIdAndCategoryIdV2
        //instance.securityGetSecurityGroupRightsByGroupIdAndCategoryIdV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityGetSecurityGroupRightsByGroupNameAndCategoryNameV1', function() {
      it('should call securityGetSecurityGroupRightsByGroupNameAndCategoryNameV1 successfully', function(done) {
        //uncomment below and update the code to test securityGetSecurityGroupRightsByGroupNameAndCategoryNameV1
        //instance.securityGetSecurityGroupRightsByGroupNameAndCategoryNameV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityGetSecurityGroupRightsByGroupNameAndCategoryNameV2', function() {
      it('should call securityGetSecurityGroupRightsByGroupNameAndCategoryNameV2 successfully', function(done) {
        //uncomment below and update the code to test securityGetSecurityGroupRightsByGroupNameAndCategoryNameV2
        //instance.securityGetSecurityGroupRightsByGroupNameAndCategoryNameV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityGetSecurityGroupRightsForCurrentUserByCategoryIdV1', function() {
      it('should call securityGetSecurityGroupRightsForCurrentUserByCategoryIdV1 successfully', function(done) {
        //uncomment below and update the code to test securityGetSecurityGroupRightsForCurrentUserByCategoryIdV1
        //instance.securityGetSecurityGroupRightsForCurrentUserByCategoryIdV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityGetSecurityGroupRightsForCurrentUserByCategoryIdV2', function() {
      it('should call securityGetSecurityGroupRightsForCurrentUserByCategoryIdV2 successfully', function(done) {
        //uncomment below and update the code to test securityGetSecurityGroupRightsForCurrentUserByCategoryIdV2
        //instance.securityGetSecurityGroupRightsForCurrentUserByCategoryIdV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityGetSecurityGroupRightsForCurrentUserByCategoryNameV1', function() {
      it('should call securityGetSecurityGroupRightsForCurrentUserByCategoryNameV1 successfully', function(done) {
        //uncomment below and update the code to test securityGetSecurityGroupRightsForCurrentUserByCategoryNameV1
        //instance.securityGetSecurityGroupRightsForCurrentUserByCategoryNameV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityGetSecurityGroupRightsForCurrentUserByCategoryNameV2', function() {
      it('should call securityGetSecurityGroupRightsForCurrentUserByCategoryNameV2 successfully', function(done) {
        //uncomment below and update the code to test securityGetSecurityGroupRightsForCurrentUserByCategoryNameV2
        //instance.securityGetSecurityGroupRightsForCurrentUserByCategoryNameV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityGetSecurityGroupsV1', function() {
      it('should call securityGetSecurityGroupsV1 successfully', function(done) {
        //uncomment below and update the code to test securityGetSecurityGroupsV1
        //instance.securityGetSecurityGroupsV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityGetSecurityGroupsV2', function() {
      it('should call securityGetSecurityGroupsV2 successfully', function(done) {
        //uncomment below and update the code to test securityGetSecurityGroupsV2
        //instance.securityGetSecurityGroupsV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityGetUsersInSecurityGroupV1', function() {
      it('should call securityGetUsersInSecurityGroupV1 successfully', function(done) {
        //uncomment below and update the code to test securityGetUsersInSecurityGroupV1
        //instance.securityGetUsersInSecurityGroupV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityGetUsersInSecurityGroupV2', function() {
      it('should call securityGetUsersInSecurityGroupV2 successfully', function(done) {
        //uncomment below and update the code to test securityGetUsersInSecurityGroupV2
        //instance.securityGetUsersInSecurityGroupV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
