/**
 * Cherwell Rest API
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CherwellRestApi);
  }
}(this, function(expect, CherwellRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CherwellRestApi.TeamsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TeamsApi', function() {
    describe('teamsAddUserToTeamByBatchV1', function() {
      it('should call teamsAddUserToTeamByBatchV1 successfully', function(done) {
        //uncomment below and update the code to test teamsAddUserToTeamByBatchV1
        //instance.teamsAddUserToTeamByBatchV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsAddUserToTeamV1', function() {
      it('should call teamsAddUserToTeamV1 successfully', function(done) {
        //uncomment below and update the code to test teamsAddUserToTeamV1
        //instance.teamsAddUserToTeamV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsAddUserToTeamV2', function() {
      it('should call teamsAddUserToTeamV2 successfully', function(done) {
        //uncomment below and update the code to test teamsAddUserToTeamV2
        //instance.teamsAddUserToTeamV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsDeleteTeamV1', function() {
      it('should call teamsDeleteTeamV1 successfully', function(done) {
        //uncomment below and update the code to test teamsDeleteTeamV1
        //instance.teamsDeleteTeamV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsGetTeamV1', function() {
      it('should call teamsGetTeamV1 successfully', function(done) {
        //uncomment below and update the code to test teamsGetTeamV1
        //instance.teamsGetTeamV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsGetTeamsV1', function() {
      it('should call teamsGetTeamsV1 successfully', function(done) {
        //uncomment below and update the code to test teamsGetTeamsV1
        //instance.teamsGetTeamsV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsGetTeamsV2', function() {
      it('should call teamsGetTeamsV2 successfully', function(done) {
        //uncomment below and update the code to test teamsGetTeamsV2
        //instance.teamsGetTeamsV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsGetUsersTeamsV1', function() {
      it('should call teamsGetUsersTeamsV1 successfully', function(done) {
        //uncomment below and update the code to test teamsGetUsersTeamsV1
        //instance.teamsGetUsersTeamsV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsGetUsersTeamsV2', function() {
      it('should call teamsGetUsersTeamsV2 successfully', function(done) {
        //uncomment below and update the code to test teamsGetUsersTeamsV2
        //instance.teamsGetUsersTeamsV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsGetWorkgroupsV1', function() {
      it('should call teamsGetWorkgroupsV1 successfully', function(done) {
        //uncomment below and update the code to test teamsGetWorkgroupsV1
        //instance.teamsGetWorkgroupsV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsGetWorkgroupsV2', function() {
      it('should call teamsGetWorkgroupsV2 successfully', function(done) {
        //uncomment below and update the code to test teamsGetWorkgroupsV2
        //instance.teamsGetWorkgroupsV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsRemoveCustomerFromWorkgroupV1', function() {
      it('should call teamsRemoveCustomerFromWorkgroupV1 successfully', function(done) {
        //uncomment below and update the code to test teamsRemoveCustomerFromWorkgroupV1
        //instance.teamsRemoveCustomerFromWorkgroupV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsRemoveUserFromTeamV1', function() {
      it('should call teamsRemoveUserFromTeamV1 successfully', function(done) {
        //uncomment below and update the code to test teamsRemoveUserFromTeamV1
        //instance.teamsRemoveUserFromTeamV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsRemoveUserFromTeamV2', function() {
      it('should call teamsRemoveUserFromTeamV2 successfully', function(done) {
        //uncomment below and update the code to test teamsRemoveUserFromTeamV2
        //instance.teamsRemoveUserFromTeamV2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsSaveTeamMemberV1', function() {
      it('should call teamsSaveTeamMemberV1 successfully', function(done) {
        //uncomment below and update the code to test teamsSaveTeamMemberV1
        //instance.teamsSaveTeamMemberV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsSaveTeamV1', function() {
      it('should call teamsSaveTeamV1 successfully', function(done) {
        //uncomment below and update the code to test teamsSaveTeamV1
        //instance.teamsSaveTeamV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsSaveWorkgroupMemberV1', function() {
      it('should call teamsSaveWorkgroupMemberV1 successfully', function(done) {
        //uncomment below and update the code to test teamsSaveWorkgroupMemberV1
        //instance.teamsSaveWorkgroupMemberV1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
